### ISSUE TITLE
Make a better About page

### ISSUE THREAD

**Issue by corbindavenport** [whatdevice/whatdevice.github.io#6]
The About popup should be turned into a complete page, with some added info like:

- Links to the GitHub project
- Attribution for all the components that WhatDevice uses
- Detailed info about how WhatDevice works

**Comment by mistermantas** [comment]
Are you sure it even needs a full about page, to be honest? There's a link to the GitHub on the first alert, there's a bug tracker link, and the only thing you could really add is attribution, which is jQuery, Bootstrap, etc. Not even that much, don't you think?

**Comment by corbindavenport** [comment]
It doesn't really need one, but I'd like to have everything in one place. The GitHub link on the front page would probably be removed once the About page is added in.
