### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by Atnode** [whatdevice/whatdevice.github.io#8]
WhatDevice shows that I use Windows 8 while it is Windows 10.

**Comment by corbindavenport** [comment]
What browser are you using? Are you using any user agent changer extension?

**Comment by Atnode** [comment]
I use Firefox 55.0b10 (64 bits).
I don't use an user agent changer extension.

**Comment by corbindavenport** [comment]
Can you paste your WhatDevice system report? Click the Share results menu and click 'Copy to clipboard'.

**Comment by Atnode** [comment]
---- WHAT-DEVICE.COM RESULTS ----
Generated: Mon Jul 24 2017 13:53:56

-- DEVICE INFO --
Manufacturer: null
Product: null
Operating system: Windows 8 64-bit
Display resolution: 1920x1080 (may be inaccurate)
Display color depth: 24
GPU: NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0

-- BROWSER INFO --
Browser: Firefox 55.0
Rendering engine: Gecko
Cookies enabled: true
User agent string: Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0

-- CONNECTED DEVICES --
Unable to retrieve list of connected devices due to API limitations.

**Comment by corbindavenport** [comment]
I can't duplicate this, it might have been a Firefox bug that was fixed.
